#ifndef SRC_COMPPREFSAUTONOMOUS_H_
#define SRC_COMPPREFSAUTONOMOUS_H_

// length with the bumpers!
#define BOT_LENGTH_BUMPERS 42.0
#define BOT_WIDTH_BUMPERS 36.0

#define DRIVE_STRAIGHT_LOW 0.20
#define DRIVE_STRAIGHT_HIGH 0.45

#define SWITCH_DISTANCE 140.0

#define SIDE_OF_SWITCH_DISTANCE 169.0
#define ARM_ANGLE2 80.0
#define EDGE_OF_SWITCH_DISTANCE 85.0

#define SIDE_OF_SCALE_DISTANCE 325.0
#define ARM_ANGLE3 180.0
#define EDGE_OF_SCALE_DISTANCE 71.0

#define HALF_OF_SWITCH_DISTANCE 70.0
#define FLUSH_WITH_SWITCH 154.0
#define ARM_ANGLE4 80.0
#define FRONT_OF_SWITCH_DISTANCE 70.0

#define TOP_OF_SWITCH_DISTANCE 0.0
#define FLUSH_WITH_SCALE 0.0
#define FRONT_OF_SCALE_DISTANCE 0.0
#define ARM_ANGLE5 80.0

#define ARM_ANGLE6 80.0

#endif
