#ifndef SRC_COMPPREFSAUTONOMOUS_H_
#define SRC_COMPPREFSAUTONOMOUS_H_

#define SWITCH_DISTANCE 97.0

#define SIDE_OF_SWITCH_DISTANCE 149.0
#define ARM_ANGLE2 60.0
#define EDGE_OF_SWITCH_DISTANCE 149.0

#define SIDE_OF_SCALE_DISTANCE 0.0
#define ARM_ANGLE3 160.0
#define EDGE_OF_SCALE_DISTANCE 0.0

#define HALF_OF_SWITCH_DISTANCE 0.0
#define FLUSH_WITH_SWITCH 0.0
#define ARM_ANGLE4 60.0
#define FRONT_OF_SWITCH_DISTANCE 0.0

#define TOP_OF_SWITCH_DISTANCE 0.0
#define FLUSH_WITH_SCALE 0.0
#define FRONT_OF_SCALE_DISTANCE 0.0
#define ARM_ANGLE5 60.0

#endif
