#ifndef SRC_PRACTICEPREFSAUTONOMOUS_H_
#define SRC_PRACTICEPREFSAUTONOMOUS_H_

// length with the bumpers!
#define BOT_LENGTH_BUMPERS 36.0
#define BOT_WIDTH_BUMPERS 28.0

#define DRIVE_STRAIGHT_LOW 0.3
#define DRIVE_STRAIGHT_HIGH 0.5

#define SWITCH_DISTANCE 140.0

#define ARM_TIMEOUT_SECONDS 10.0
#define AUTON_ROLLER_SPEED -0.55

#define SIDE_OF_SWITCH_DISTANCE 169.0
#define EDGE_OF_SWITCH_DISTANCE 85.0

#define SIDE_OF_SCALE_DISTANCE 325.0
#define EDGE_OF_SCALE_DISTANCE 40.0

#define HALF_OF_SWITCH_DISTANCE 70.0
#define FLUSH_WITH_SWITCH 154.0
#define FRONT_OF_SWITCH_DISTANCE 70.0

#define TOP_OF_SWITCH_DISTANCE 0.0
#define FLUSH_WITH_SCALE 0.0
#define FRONT_OF_SCALE_DISTANCE 0.0

#define SEVEN_TO_SCALE_DISTANCE 0.0
#define SEVEN_MOVE_BACK_SCALE_DIST 0.0
#define SEVEN_TO_SWITCH_DISTANCE 0.0
#define SEVEN_MOVE_BACK_SWITCH_DIST 0.0

#define REST_ANGLE 60.0
#define SWITCH_ANGLE 80.0
#define SCALE_ANGLE 190.0

#endif
